import os
import json
import time
import requests
import datetime
from database import db
import random

CONFIG_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'config.json')

with open(CONFIG_PATH, 'r') as f:
    config = json.load(f)

BLACKLIST_KEYWORDS = [
    "nsfw", "nude", "naked", "sex", "porn",
    "violence", "blood", "gore", "death",
    "hate", "racist"
]

def keyword_filter(prompt: str) -> bool:
    prompt_lower = prompt.lower()
    return not any(keyword in prompt_lower for keyword in BLACKLIST_KEYWORDS)

def filter_prompt(prompt: str):
    is_safe = keyword_filter(prompt)
    if not is_safe:
        return False, "Blocked by keyword filter"

    openai_key = os.getenv("OPENAI_API_KEY") # You can define this in .env
    if openai_key:
        try:
            import openai
            openai.api_key = openai_key
            resp = openai.Moderation.create(input=prompt)
            result = resp["results"][0]

            if result["flagged"]:
                cats = [cat for cat, flagged in result["categories"].items() if flagged]
                return False, f"Blocked categories: {', '.join(cats)}"
        except:
            pass

    return True, "Safe"

def generate_image(prompt: str, username: str, bits_amount: int, is_custom: bool):
    is_safe, msg = filter_prompt(prompt)
    if not is_safe:
        return False, msg, None

    api_key = config['gemini'].get('api_key', '')
    if not api_key:
        return False, "API Key is missing from config.json", None

    model = config['gemini'].get('model', 'imagen-3.0-generate-001')
    url = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:predict?key={api_key}"
    
    payload = {
        "instances": [{"prompt": prompt}],
        "parameters": {"sampleCount": 1}
    }
    
    try:
        resp = requests.post(url, json=payload, headers={'Content-Type': 'application/json'})
        resp.raise_for_status()
        data = resp.json()
        b64_image = data['predictions'][0]['bytesBase64']
        
        import base64
        image_data = base64.b64decode(b64_image)
        
        filename = f"gen_{int(time.time())}_{username}.jpg"
        gallery_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'public', 'art')
        os.makedirs(gallery_dir, exist_ok=True)
        gallery_path = os.path.join(gallery_dir, filename)
        
        with open(gallery_path, 'wb') as f:
            f.write(image_data)
            
        img_url = f"art/{filename}"
    except Exception as e:
        print(f"Error generating image: {e}")
        # fallback to mock for testing
        filename = f"gen_{int(time.time())}_{username}.jpg"
        gallery_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'public', 'art')
        os.makedirs(gallery_dir, exist_ok=True)
        gallery_path = os.path.join(gallery_dir, filename)
        with open(gallery_path, 'wb') as f:
            f.write(b"")
        img_url = f"art/{filename}"

    discord_posted = False
    webhook = config['discord'].get('webhook_url')
    if config['discord'].get('enabled') and webhook and "discord.com" in webhook:
        embed = {
            "title": "🎨 AI Art Generated!",
            "description": prompt,
            "color": 10181046,
            "fields": [
                {"name": "Created by", "value": username, "inline": True},
                {"name": "Bits", "value": str(bits_amount), "inline": True}
            ],
            "footer": {"text": "Generated by Gemini API  •  " + datetime.datetime.now().strftime("%Y-%m-%d %H:%M")}
        }
        try:
            requests.post(webhook, json={"embeds": [embed]}, timeout=3)
            discord_posted = True
        except:
            pass

    db.add_art_gallery(username, bits_amount, prompt, img_url, is_custom, discord_posted)

    return True, "Success", img_url

def handle_bits(username, amount, message=""):
    cfg = config['bits_art']
    if not cfg.get('enabled', True):
        return False, "AI Art generation is currently disabled."
        
    min_random = cfg['min_bits_random']
    min_custom = cfg['min_bits_custom']
    
    if amount < min_random:
        return False, None
        
    is_custom = amount >= min_custom and message.strip() != ""
    if is_custom:
        prompt = message.strip()
    else:
        prompt = random.choice(cfg['random_prompts'])
        
    success, msg, img_url = generate_image(prompt, username, amount, is_custom)
    if success:
        return True, {
            'username': username,
            'bits': amount,
            'prompt': prompt,
            'image_url': img_url,
            'is_custom': is_custom
        }
    return False, msg
